# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/xillydemo.xdc

# IP: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vga_fifo/vga_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_fifo || ORIG_REF_NAME==vga_fifo}]

# IP: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/fifo_8x2048/fifo_8x2048.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_8x2048 || ORIG_REF_NAME==fifo_8x2048}]

# Block Designs: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/vivado_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system || ORIG_REF_NAME==vivado_system}]

# IP: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xillybus_lite_0_0/vivado_system_xillybus_lite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_xillybus_lite_0_0 || ORIG_REF_NAME==vivado_system_xillybus_lite_0_0}]

# IP: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xillybus_ip_0_0/vivado_system_xillybus_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_xillybus_ip_0_0 || ORIG_REF_NAME==vivado_system_xillybus_ip_0_0}]

# IP: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xillyvga_0_0/vivado_system_xillyvga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_xillyvga_0_0 || ORIG_REF_NAME==vivado_system_xillyvga_0_0}]

# IP: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_0/vivado_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_processing_system7_0_0 || ORIG_REF_NAME==vivado_system_processing_system7_0_0}]

# IP: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==vivado_system_rst_processing_system7_0_100M_0}]

# IP: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xlconcat_0_0/vivado_system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_xlconcat_0_0 || ORIG_REF_NAME==vivado_system_xlconcat_0_0}]

# IP: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_axi_periph_0/vivado_system_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==vivado_system_processing_system7_0_axi_periph_0}]

# IP: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xbar_0/vivado_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_xbar_0 || ORIG_REF_NAME==vivado_system_xbar_0}]

# IP: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_0/vivado_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_auto_pc_0 || ORIG_REF_NAME==vivado_system_auto_pc_0}]

# IP: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_1/vivado_system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_auto_pc_1 || ORIG_REF_NAME==vivado_system_auto_pc_1}]

# IP: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_2/vivado_system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_auto_pc_2 || ORIG_REF_NAME==vivado_system_auto_pc_2}]

# IP: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_3/vivado_system_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_auto_pc_3 || ORIG_REF_NAME==vivado_system_auto_pc_3}]

# XDC: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_0/vivado_system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vivado_system_processing_system7_0_0 || ORIG_REF_NAME==vivado_system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==vivado_system_rst_processing_system7_0_100M_0}]

# XDC: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==vivado_system_rst_processing_system7_0_100M_0}]

# XDC: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xbar_0/vivado_system_xbar_0_ooc.xdc

# XDC: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_0/vivado_system_auto_pc_0_ooc.xdc

# XDC: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_1/vivado_system_auto_pc_1_ooc.xdc

# XDC: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_2/vivado_system_auto_pc_2_ooc.xdc

# XDC: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_3/vivado_system_auto_pc_3_ooc.xdc

# XDC: /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/vivado_system_ooc.xdc
