# 
# Synthesis run script generated by Vivado
# 

set_msg_config  -id {BD 41-968}  -string {{xillybus_S_AXI}}  -new_severity {INFO} 
set_msg_config  -id {BD 41-967}  -string {{xillybus_ip_0/xillybus_M_AXI}}  -new_severity {INFO} 
set_msg_config  -id {BD 41-967}  -string {{xillybus_ip_0/xillybus_S_AXI}}  -new_severity {INFO} 
set_msg_config  -id {BD 41-678}  -string {{xillybus_S_AXI/Reg}}  -new_severity {INFO} 
set_msg_config  -id {BD 41-1356}  -string {{xillybus_S_AXI/Reg}}  -new_severity {INFO} 
set_msg_config  -id {BD 41-759}  -string {{xlconcat_0/In}}  -new_severity {INFO} 
set_msg_config  -id {Netlist 29-160}  -string {{vivado_system_processing_system7}}  -new_severity {INFO} 
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/xillybus/vivado/xillydemo.cache/wt [current_project]
set_property parent.project_path /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/xillybus/vivado/xillydemo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado-ip [current_project]
add_files -quiet /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/xillybus/vivado/xillydemo.runs/fifo_32x512_synth_1/fifo_32x512.dcp
set_property used_in_implementation false [get_files /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/xillybus/vivado/xillydemo.runs/fifo_32x512_synth_1/fifo_32x512.dcp]
read_ip /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vga_fifo/vga_fifo.xci
set_property used_in_implementation false [get_files -all /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vga_fifo/vga_fifo/vga_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vga_fifo/vga_fifo/vga_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vga_fifo/vga_fifo_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vga_fifo/vga_fifo.dcp]
set_property is_locked true [get_files /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vga_fifo/vga_fifo.xci]

read_ip /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/fifo_8x2048/fifo_8x2048.xci
set_property used_in_implementation false [get_files -all /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/fifo_8x2048/fifo_8x2048/fifo_8x2048.xdc]
set_property used_in_implementation false [get_files -all /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/fifo_8x2048/fifo_8x2048_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/fifo_8x2048/fifo_8x2048.dcp]
set_property is_locked true [get_files /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/fifo_8x2048/fifo_8x2048.xci]

add_files /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/vivado_system.bd
set_property used_in_implementation false [get_files -all /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_0/vivado_system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xbar_0/vivado_system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_0/vivado_system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_1/vivado_system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_2/vivado_system_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_3/vivado_system_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/vivado_system_ooc.xdc]
set_property is_locked true [get_files /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/vivado_system/vivado_system.bd]

read_verilog -library xil_defaultlib {
  /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/xillybus/src/xillydemo.v
  /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/xillybus/src/xillybus_core.v
  /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/xillybus/src/xillybus.v
  /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/xillybus/src/system.v
  /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/xillybus/src/smbus.v
  /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/xillybus/src/i2s_audio.v
  /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/xillybus/src/fpga-design/dut.v
  /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/xillybus/src/fifo_8x2048.v
  /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/xillybus/src/fifo_32x512.v
  /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/system.v
}
set_property edif_extra_search_paths /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/cores [current_fileset]
read_xdc /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/xillydemo.xdc
set_property used_in_implementation false [get_files /home/student/mq58/MengProj/meng-reconfigurable-computing/cordic_tutorial/amdpool/zedboard_project/vivado-essentials/xillydemo.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top xillydemo -part xc7z020clg484-1
write_checkpoint -noxdef xillydemo.dcp
catch { report_utilization -file xillydemo_utilization_synth.rpt -pb xillydemo_utilization_synth.pb }
